import { component$ } from "@builder.io/qwik";
import { Button } from "~/components/button";
import { PageLayout } from "~/components/page-layout";

export default component$(() => {
  return (
    <PageLayout>
      <h1 q:slot="head" class="text-5xl leading-snug">
        AI-Generated Church Quotes Disclosure
      </h1>

      <div class="flex max-w-4xl flex-col flex-wrap justify-stretch gap-10 text-purple [&>*]:min-w-[200px] [&>*]:flex-auto [&>*]:basis-[25%]">
        <p>
          <strong>Purpose of the AI Tool:</strong> This AI tool is designed to
          assist church administrators by providing inspirational and
          thought-provoking quotes for use on church signs. These quotes are
          generated automatically using advanced algorithms trained on a diverse
          dataset of religious texts, sermons, and famous theological
          quotations.
        </p>
        <p>
          <strong>How It Works:</strong> Our AI uses natural language processing
          (NLP) techniques to craft messages that align with specified themes or
          topics chosen by the user. The goal is to offer creative and engaging
          content that resonates with the community and supports the church's
          messaging goals.
        </p>
        <p>
          <strong>Benefits:</strong> The AI tool aims to save time and effort in
          creating new signs, offering a variety of messages that can be
          tailored to different occasions and themes. It is intended to enhance
          the church's engagement with the community through thoughtful and
          relevant content.
        </p>
        <p>
          <strong>User Input and Customization:</strong> Users have the ability
          to select themes and adjust the generated quotes to better fit their
          specific needs and the context of their community. This interaction
          ensures that the content remains relevant and closely aligned with the
          church’s values and doctrinal stance.
        </p>
        <p>
          <strong>Ethical Considerations and Authenticity:</strong> We are
          committed to maintaining the highest standards of accuracy and
          theological appropriateness in the quotes generated by our AI.
          However, we encourage our users to review all content to ensure it
          aligns with their church’s teachings and community values.
        </p>
        <p>
          <strong>Privacy and Data Security:</strong> We prioritize the privacy
          and security of our users' data. No personal information is required
          to use this tool, and we do not store any data generated during the
          quote creation process without explicit permission.
        </p>
        <p>
          <strong>Limitations and Non-Liability:</strong> While we strive for
          accuracy and relevance, the quotes generated by AI may not always
          perfectly reflect the depth of human-generated content. Users are
          advised to review and modify any content before public display. Please
          note that our organization does not take responsibility for any
          content generated by this AI tool, nor are we liable for any direct or
          indirect consequences that arise from its use.
        </p>
        <p>
          <strong>Feedback and Improvements:</strong> We welcome feedback on the
          AI tool and are committed to continuous improvement to better serve
          our users and their communities. Please contact us with suggestions or
          concerns regarding the AI-generated content.
        </p>
        <p>
          For any further questions or to provide feedback, please do not
          hesitate to contact us through our website.
        </p>
      </div>
      <Button color="green">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
          class="h-6 w-6"
        >
          <path d="M10.464 8.746c.227-.18.497-.311.786-.394v2.795a2.252 2.252 0 0 1-.786-.393c-.394-.313-.546-.681-.546-1.004 0-.323.152-.691.546-1.004ZM12.75 15.662v-2.824c.347.085.664.228.921.421.427.32.579.686.579.991 0 .305-.152.671-.579.991a2.534 2.534 0 0 1-.921.42Z" />
          <path
            fill-rule="evenodd"
            d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 6a.75.75 0 0 0-1.5 0v.816a3.836 3.836 0 0 0-1.72.756c-.712.566-1.112 1.35-1.112 2.178 0 .829.4 1.612 1.113 2.178.502.4 1.102.647 1.719.756v2.978a2.536 2.536 0 0 1-.921-.421l-.879-.66a.75.75 0 0 0-.9 1.2l.879.66c.533.4 1.169.645 1.821.75V18a.75.75 0 0 0 1.5 0v-.81a4.124 4.124 0 0 0 1.821-.749c.745-.559 1.179-1.344 1.179-2.191 0-.847-.434-1.632-1.179-2.191a4.122 4.122 0 0 0-1.821-.75V8.354c.29.082.559.213.786.393l.415.33a.75.75 0 0 0 .933-1.175l-.415-.33a3.836 3.836 0 0 0-1.719-.755V6Z"
            clip-rule="evenodd"
          />
        </svg>
        Help children in need
      </Button>
    </PageLayout>
  );
});
